version: '3.8'

services:
  backend:
    image: storebackend
    environment: 
      - PORT=${PORT}
      - SECRET=${SECRET}
      - MONGODB_URI=${MONGODB_URI}
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 4000:4000
  frontend:
    image: storefrontend
    build:
      context: . 
      dockerfile: ./frontend/Dockerfile 
    ports:
      - 3000:80
    container_name: storefrontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend # wait for the frontend container to be started
      - backend